zt:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: admin
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    base-packages: com.zt.masterSlaveDS.dao
    mapperLocations: classpath:mapping/*.xml
    driver-class-name: com.mysql.cj.jdbc.Driver
    tx-aop-expression: execution(* com.zt.masterSlaveDS.service.*.*Service*.*(..))
    slaves:
      slave1:
        url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      slave2:
        url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&serverTimezone=Asia/Shanghai
        username: root
        password: 123456